### ISSUE TITLE
HTTP Download

### ISSUE THREAD

**Issue by ypid** [wtanaka/ansible-teamviewer#5]
Please download software via HTTPS instead of legacy HTTP to ensure at least a tiny bit of authenticity in the lack of signatures which https://teamviewer.com seems to be unable to provide.

Ref: https://github.com/wtanaka/ansible-role-teamviewer/blob/master/vars/main.yml
Ref: https://docs.debops.org/en/latest/debops-policy/docs/software-source-policy.html

**Comment by wtanaka** [comment]
@ypid done.

What is debops BTW  I've seen it before on ansible galaxy?  It seems like just "some project" (no offense if project is yours!) as opposed to an authoritative definition of what is "legacy" like something like IETF would be.

**Comment by ypid** [comment]
Thanks.

Hm, well, it is not my project but I am [one of the developers](https://docs.debops.org/en/latest/debops-keyring/docs/entities.html), refer to my [user page in the DebOps wiki](https://wiki.debops.org/wiki:user:ypid). I came to DebOps 2 years ago and it is great. If you are using Debian, Ansible and are serious about CM, there is no way around DebOps I would say :wink:

**Comment by drybjed** [comment]
Hi, the author of the DebOps project here. It's not "official" as in endorsed by any trustworthy organization, but [we are trying to improve this](https://bestpractices.coreinfrastructure.org/projects/237) as a start. The idea behind DebOps is to have a secure, audited and stable base for your Debian/Ubuntu hosts. Check it out if you're interested. :-)
